### ISSUE TITLE
MoreRoleColors could not be started

### ISSUE THREAD

**Issue by TheGreatTaz** [DaddyBoard/BD-Plugins#1]
![image](https://github.com/user-attachments/assets/fa4527dc-5636-47ad-8082-bc5d191e0671)

**Comment by DaddyBoard** [comment]
Please update BetterDiscord Core. 

Discord settings > scroll down to BD area, > Updates > Update Core. (should be version 1.11.0)

**Comment by TheGreatTaz** [comment]
i had already done that but it apparently didn't work, I had to update using the launcher
