### ISSUE TITLE
MoreRoleColors not correctly showing the current setting status

### ISSUE THREAD

**Issue by Enrico9431** [DaddyBoard/BD-Plugins#2]
It seems like that all settings apart from those under the General Coloring category will still show as enabled when you open the plugin settings again.

**Comment by DaddyBoard** [comment]
You are right, sorry about that. Will get an update out asap.

**Comment by DaddyBoard** [comment]
https://github.com/DaddyBoard/BD-Plugins/commit/4b31efc3d9ace800720b08cb9a023180dff7eca6 This has been fixed. Thank you for reporting
