### ISSUE TITLE
Message content gets colored

### ISSUE THREAD

**Issue by dumpedsoul** [DaddyBoard/BD-Plugins#4]
Since installing this plugin, I noticed the content of messages getting colored as the role color, respectively.
At times, hovering over the messages make the text appear white again, only to turn back to the role color soon after.
There being no setting to even enable/disable this, it leaves me no option other than disabling the plugin entirely until fixed.
![Discord_YiiCCy7wsg](https://github.com/user-attachments/assets/b38795c2-213c-4b55-8dda-64fe6313c8f9)

**Comment by DaddyBoard** [comment]
Hi @dumpedsoul 

There is a setting for this, that is disabled by default, which means you've turned it on 
![Discord_ELfuF25CN0](https://github.com/user-attachments/assets/7f02e13c-9fae-48f6-9bc9-17c91608357c)

**Comment by dumpedsoul** [comment]
Oh, well the setting being described as the main feature of the plugin sure is confusing. 😅
Thanks for clearing it up!
